// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Bindings")>]
[<assembly: AssemblyProductAttribute("MordhauBuddy")>]
[<assembly: AssemblyDescriptionAttribute("Compilation of Mordhau Tools")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Bindings.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Bindings"
    let [<Literal>] AssemblyProduct = "MordhauBuddy"
    let [<Literal>] AssemblyDescription = "Compilation of Mordhau Tools"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Bindings.Tests"
