name: $(Rev:r)
trigger:
  branches:
    include:
    - '*'
pool:
  vmImage: 'windows-2019'
variables:
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  isFBranch: $[contains(['refs/heads/master', 'refs/heads/Develop'], variables['Build.SourceBranch'])]
stages:
- stage: Setup
  jobs:
  - job: Install dotnet
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core CLI'
      inputs:
        packageType: sdk
        version: 2.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
- stage: Test
  jobs:
  - job: Lint code
    steps: 
    - powershell: '.\build.cmd -t Lint'
      displayName: 'Perform linting'
      failOnStderr: true
    - powershell: 'if(Test-Path .\bin\Lint*.xml -PathType Leaf) {echo "##vso[task.setVariable variable=LintFileExists]true"}'
      displayName: 'Check for lint results to publish'
    - task: PublishTestResults@2
      displayName: 'Publish linting results'
      condition: eq(variables['LintFileExists'], 'true')
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: 'bin/Lint*.xml'
        failTaskOnFailedTests: true
  - job: Run tests
    steps:
    - powershell: '.\build.cmd -t RunTests'
      displayName: 'Run tests'
      failOnStderr: true
    - powershell: 'if(Test-Path .\bin\Test*.xml -PathType Leaf) {echo "##vso[task.setVariable variable=TestFileExists]true"}'
      displayName: 'Check for test results to publish'
    - task: PublishTestResults@2
      displayName: 'Publish testing results'
      condition: eq(variables['TestFileExists'], 'true')
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: 'bin/Test*.xml'
        failTaskOnFailedTests: true
- stage: Build
  - job: Build solution and documentation
    steps:
    - powershell: '.\build.cmd'
      failOnStderr: true
