// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fable.Electron")>]
[<assembly: AssemblyProductAttribute("MordhauBuddy")>]
[<assembly: AssemblyDescriptionAttribute("Compilation of Mordhau Tools")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
[<assembly: InternalsVisibleToAttribute("Fable.Electron.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.Electron"
    let [<Literal>] AssemblyProduct = "MordhauBuddy"
    let [<Literal>] AssemblyDescription = "Compilation of Mordhau Tools"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Debug"
    let [<Literal>] InternalsVisibleTo = "Fable.Electron.Tests"
