// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.CompilerServices

[<assembly:AssemblyTitleAttribute("Shared")>]
[<assembly:AssemblyProductAttribute("MordhauBuddy")>]
[<assembly:AssemblyDescriptionAttribute("Compilation of Mordhau Tools")>]
[<assembly:AssemblyVersionAttribute("0.0.1")>]
[<assembly:AssemblyFileVersionAttribute("0.0.1")>]
[<assembly:AssemblyConfigurationAttribute("Release")>]
[<assembly:InternalsVisibleToAttribute("Shared.Tests")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "Shared"

    [<Literal>]
    let AssemblyProduct = "MordhauBuddy"

    [<Literal>]
    let AssemblyDescription = "Compilation of Mordhau Tools"

    [<Literal>]
    let AssemblyVersion = "0.0.1"

    [<Literal>]
    let AssemblyFileVersion = "0.0.1"

    [<Literal>]
    let AssemblyConfiguration = "Release"

    [<Literal>]
    let InternalsVisibleTo = "Shared.Tests"
