// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Shared")>]
[<assembly: AssemblyProductAttribute("MordhauBuddy")>]
[<assembly: AssemblyDescriptionAttribute("Compilation of Mordhau Tools")>]
[<assembly: AssemblyVersionAttribute("1.3.0")>]
[<assembly: AssemblyFileVersionAttribute("1.3.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Shared.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Shared"
    let [<Literal>] AssemblyProduct = "MordhauBuddy"
    let [<Literal>] AssemblyDescription = "Compilation of Mordhau Tools"
    let [<Literal>] AssemblyVersion = "1.3.0"
    let [<Literal>] AssemblyFileVersion = "1.3.0"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Shared.Tests"
