// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Renderer")>]
[<assembly: AssemblyProductAttribute("MordhauBuddy")>]
[<assembly: AssemblyDescriptionAttribute("Compilation of Mordhau Tools")>]
[<assembly: AssemblyVersionAttribute("1.4.4")>]
[<assembly: AssemblyFileVersionAttribute("1.4.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Renderer.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Renderer"
    let [<Literal>] AssemblyProduct = "MordhauBuddy"
    let [<Literal>] AssemblyDescription = "Compilation of Mordhau Tools"
    let [<Literal>] AssemblyVersion = "1.4.4"
    let [<Literal>] AssemblyFileVersion = "1.4.4"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Renderer.Tests"
